const SPEED = 4;
const GRAVITY = 2;
const WHEEL_RADIUS = 0;
const COIN_INTERVAL = 2000;
const FUEL_MAX_WIDTH = 50;
const MAX_INTERVAL = 1000; 
const COIN_GENERATION_INTERVAL = 2000; 
const FUEL_INTERVAL = 3000;

const FUEL_REGENERATION_INTERVAL = 6000; // 6 seconds in milliseconds
const FUEL_REGENERATION_DELAY = 3000; 
